### ISSUE TITLE
Feedback on the notebook theme

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos_jekyll_theme#13]
@jbosch-noaa, @mwengren, and @lukecampbell please take a look at how the notebook-page using this theme looks like and let me know if you have any suggestions, comments, etc.

http://ocefpaf.github.io/notebooks_demos/

@rsignell-usgs mentioned that the fonts are not OK. The problem that we have there is that the amount of code text is almost the same of the amount of non-code text and, together with the code warnings text it renders a weird reading experience. We could try to use the same fonts for code and normal text but that also look a like bit weird.

BTW the original theme have a `$monospace` font family for code. See  https://github.com/ioos/ioos_jekyll_theme/blob/gh-pages/_sass/_syntax.scss#L30

I changed that to `Source code pro` in https://github.com/ioos/ioos_jekyll_theme/pull/12/files#diff-f503bd396089f8d30333b57756833d40R12

The `Source code pro` looks better in my laptop but terrible in Rich's not sure why yet.

**Comment by lukecampbell** [comment]
Is there a way to mute the warnings?

**Comment by ocefpaf** [comment]
> Is there a way to mute the warnings?

Yes. But those are part of the notebooks there. (In other cases I do silence them.)

**Comment by mwengren** [comment]
@ocefpaf, they look pretty good to me, but I'm not sure the standard to
compare against.  Although I think there may be some conflicts in the CSS,
at least when I view in Chrome.

I'm not sure what is intended, but it looks like the input code blocks,
where the HTML looks like this:

<pre class="highlight">
<code>
...
</code>
</pre>

There's a CSS rule for <code> elements that's overriding the "Source Code
Pro" font and using "Monaco, Consolas, "Lucida Console", monospace
instead.  I see that's the $monospace font you were talking about.  Maybe
those changes aren't in effect completely in the notebook here:
http://ocefpaf.github.io/notebooks_demos/.

in general, it might look better to shrink the font a little for the code.

Micah

**Comment by rsignell-usgs** [comment]
Here's what it looks like on my Chrome.    IMHO, there are way too many fonts in arbitrary sizes, and will not lend a feeling of confidence regarding IOOS:
![2016-10-07_11-44-14](https://cloud.githubusercontent.com/assets/1872600/19196430/8a5d9daa-8c83-11e6-9111-4d256daf7841.jpg)

**Comment by ocefpaf** [comment]
Thanks for the feedback @mwengren!

> in general, it might look better to shrink the font a little for the code.

Will do, but let's get https://github.com/ioos/ioos_jekyll_theme/pull/12 and https://github.com/ioos/ioos_jekyll_theme/pull/14 in the repo first so we can start using the theme as submodule.

**Comment by ocefpaf** [comment]
Closing this. We can keep discussing it here though.
