### ISSUE TITLE
Maintain a 'master' and 'gh-pages' branch of this repo for documentation/clarity?

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos_jekyll_theme#17]
With the git submodule approach working to use this theme as an external template from another repo's GitHub.io site, we should document the steps to set this up properly so folks can use it.   

Step outline (from https://github.com/ioos/ioos_jekyll_theme/issues/4#issuecomment-252358234):
- init submodule in 'gh-pages' branch
- copy files from submodule to repo root
- configure _config.yml
- add content in Jekyll collection
- etc etc...

Suggest this info goes on a page in https://ioos.github.io/ioos_jekyll_theme site itself.   Problem is this site isn't working currently because of the changes made to the 'gh-pages' branch to accommodate the submodule approach above.  

Should we maintain a 'master' branch that has the structure of the current 'gh-pages' branch, and a separate 'gh-pages' branch to use for above documentation?  

Can you have a submodule within a branch of the same repo in order to do this without maintaining two parallel branches?  When I have time I'll try, just want to note the issue...

**Comment by ocefpaf** [comment]
> Suggest this info goes on a page in https://ioos.github.io/ioos_jekyll_theme site itself.

:+1: 

> Problem is this site isn't working currently because of the changes made to the 'gh-pages' branch to accommodate the submodule approach above.

For future reference I believe the only breaking changes are those in `_includes/head.html` and `_includes/masthead.html` from https://github.com/ioos/ioos_jekyll_theme/pull/14/commits/87ff39bf167a8d76cfeeaa966d121d6448230584, right?

> Should we maintain a 'master' branch that has the structure of the current 'gh-pages' branch, and a separate 'gh-pages' branch to use for above documentation?

That is a fine workaround.

> Can you have a submodule within a branch of the same repo in order to do this without maintaining two parallel branches?

Not sure. I will try something next week if you haven't got to it already.

**Comment by mwengren** [comment]
also _includes/scripts.html... but yes just those files with path changes.  The test.md probably should have been left out of the commit, made it rather fast.  The markdown pages in the repo can be cleaned up when we sort out the above and add 'howto' docs page to the 'gh-pages' branch, I'll just delete that page then.

**Comment by ocefpaf** [comment]
> The test.md probably should have been left out of the commit, made it rather fast. The markdown pages in the repo can be cleaned up when we sort out the above and add 'howto' docs page to the 'gh-pages' branch, I'll just delete that page then.

My bad. I was eager to move this forward and merged it as-is.

**Comment by mwengren** [comment]
@ocefpaf I'm trying to close the loop on this to make the ioos_jekyll_theme easier to work with.  

Would there be any issues with your workflow if we moved the default gh-pages branch back to master, and created a new gh-pages branch with the self-referencing submodule to host documentation on using this as a submodule as well as a cloneable example of it in action?

The documentation would go [here](https://ioos.github.io/ioos_jekyll_theme/) which of course would hopefully work again.

Can I proceed with these changes?

**Comment by ocefpaf** [comment]
> Can I proceed with these changes?

No. That is fine. I don't recall why we chose `gh-pages` in the first place.

**Comment by mwengren** [comment]
Looking more closely at it, we'll have a branch that's basically unrelated to the master branch, and never intended to be merged, but I guess that's not uncommon for github.io branches.  

Should I rewind the commit history to the initial commit before deleting/adding files to make the distinction clearer?  Or just branch from current master and delete unneeded files from present state do you think?  Thanks for your advice.

**Comment by ocefpaf** [comment]
> Should I rewind the commit history to the initial commit before deleting/adding files to make the distinction clearer? Or just branch from current master and delete unneeded files from present state do you think? 

I would go for the latter.

**Comment by mwengren** [comment]
Ok, just finished this up: https://ioos.github.io/ioos_jekyll_theme/.  

The 'gh-pages' branch now includes the master branch as a submodule.   Users can copy the 'gh-pages' branch to get a new ioos_jekyll_theme based site up and running.  Master branch is to modify the theme directly.
