### ISSUE TITLE
gh-pages `/_pages/` should be `/pages/`?

### ISSUE THREAD

**Issue by 7yl4r** [ioos/ioos_jekyll_theme#32]
We have cloned this template for use with the IOOS MBON project and made modifications [here](https://github.com/marinebon/ioos_jekyll_theme/tree/website).
I have renamed the branches there, but the following refers to the branches as named on this repo.

After cloning we were having trouble with new `.md` files created in the `_pages` on the gh-pages branch not rendering with jekyll.
The fix for this was to rename the `_pages` directory to `pages`.
I know `_pages` is the naming convention for themes, but is there a use for the `_pages` directory on the `gh-pages` branch?

**Comment by ocefpaf** [comment]
It has been a while that I don't create a new page but I recall that when creating a new one the first jekyll run renamed that for me. If that option is no longer available I'm OK renaming it here.

**Comment by mwengren** [comment]
I'm a bit rusty with this Jekyll template as well, but I think the only connection with the '_pages' name is in config.yml (see [here](https://github.com/ioos/ioos_jekyll_theme/blob/master/_config.yml#L146)).  

Maybe since this line is commented out in config.yml that is part of the problem?

**Comment by 7yl4r** [comment]
Interestingly, it does look like this config is working for the site here.
Files from both the template and the gh-pages:/_pages/ dir are working:

* gh-pages:/[template_markup](https://ioos.github.io/ioos_jekyll_theme/pages/template_markup/) 
* master:/[test.md](https://ioos.github.io/ioos_jekyll_theme/pages/test/)

I guess this means it was a configuration error on my side?
I just attempted running jekyll on a fresh install of this repo ~~but ran into a the following error so cannot confirm~~ and it works as advertised. :man_shrugging:

**Comment by 7yl4r** [comment]
I'll close this since I'm not seeing the issue anymore.
I would be happy to revisit if anyone else runs into this and reopens.
