### ISSUE TITLE
How does this relate to `documentation-theme-jekyll`?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_jekyll_theme#36]
I did a quick [search](https://github.com/ioos?q=jekyll&type=all&language=&sort=) through the IOOS GH org for `jekyll` and came across this one. Does this relate to https://github.com/ioos/documentation-theme-jekyll?

If not, since it hasn't been touched since 2019, I recommend we 'Archive' is and state we are no longer maintaining it.

**Comment by ocefpaf** [comment]
We should archive this one. It was the old theme but we are no longer using it anywhere as far as I know.

**Comment by MathewBiddle** [comment]
I'll wait for @mwengren to weigh in before doing anything drastic.
