### ISSUE TITLE
How to use this repository 

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos_jekyll_theme#4]
@jbosch-noaa following https://github.com/ioos/notebooks_demos/issues/82#issuecomment-247987834 I created this repository to host the IOOS jekyll theme. This should make it easy to contribute to the theme in one place and propagate the changes to all sites that uses it.

We can use this issue to ping users who are interested into helping/using this theme.

cc @lukecampbell

**Comment by ocefpaf** [comment]
To use this theme one must add it as a `git-submodule` to the jekyll page repository and `symlink` the three folders (`_includes`, `_layouts`, and `assets`) to the main project directory. 

``` shell
git submodule add --force https://github.com/ioos/ioos_jekyll_theme.git
ln -s ioos_jekyll_theme/assets assets
ln -s ioos_jekyll_theme/_includes _includes
ln -s ioos_jekyll_theme/_layouts _layouts
```

**Comment by mwengren** [comment]
correct thread...

@ocefpaf I've already spent some time adapting an existing Jekyll theme to make it look IOOS-like for github.io documentation for the Catalog project. Maybe we can combine these two efforts somehow? I don't know what kind of look you are going for, but I found it pretty easy to adapt a theme called 'minimal-mistakes' to give it an IOOS style. It's also pretty easy to customize in terms of the navigation menu, etc, for other projects, and has a lot of the nuts and bolts already set up in Jekyll.

Here's a link to to the working version: https://ioos.github.io/catalog/pages/registry/

**Comment by ocefpaf** [comment]
> @ocefpaf I've already spent some time adapting an existing Jekyll theme to make it look IOOS-like for github.io documentation for the Catalog project.

I've been looking for something like this for months!

> Maybe we can combine these two efforts somehow?

Yes please! I will take a look at your theme right now. I am pretty sure it is much better than this one.

> I don't know what kind of look you are going for, but I found it pretty easy to adapt a theme called 'minimal-mistakes' to give it an IOOS style.

I am not particularly married to any look as long as @jbosch-noaa approves it :smile:

**Comment by ocefpaf** [comment]
@mwengren would you agree to pull the theme from https://github.com/ioos/catalog and place it here (or a new `ioos_jekyll_theme` repository)?

In theory the `_includes`, `_layouts`, and `assets` could be common to all projects and putting them in a single repository makes it easier to contribute and use the theme.

**Comment by mwengren** [comment]
Sure, I may not be able to do right away, but will look into soon.  I think there are some other directories the theme may require.  And it probably could be cleaned up a little.

**Comment by jbosch-noaa** [comment]
@ocefpaf   and @mwengren - This sounds great!  I think the https://ioos.github.io/catalog/ site is very much what I had in mind with the sidebar navigation and such. :)

**Comment by ocefpaf** [comment]
@mwengren and @jbosch-noaa I just tested how the notebook converter would behave with the `registry` theme and here is the result: https://ocefpaf.github.io/notebooks_demos/

I really like the look and feel of the site that way! Note that the side-bar is not tested, and top-menu is not fully populated but both should work. The only snag is the `footer`. I will investigate what is going on there. (If you navigate the page you will see that the footer is not placed at the bottom of the page.)

@mwengren the `notebook` template inherits from the `default`. If you have some time please take a look and let me know if you see any obvious erros: https://github.com/ocefpaf/notebooks_demos/blob/gh-pages/_layouts/notebook.html

**Comment by mwengren** [comment]
@ocefpaf I'm not familiar with notebook converter, how it works etc, but I guess that looks like a good start.  The Jekyll theme itself uses Jekyll's sass/scss engine to compile source files into the resulting css.    

Looking at the footer issue I think the problem might be that there's an additional css file or two that's loaded inline in the page content: 
`
<link rel="stylesheet" href="/notebooks_demos/assets/css/syntax.css">
<link rel="stylesheet" href="/notebooks_demos/assets/css/style.css">
`
I think those might be overriding some styling rules in the Jekyll complied css from the header block that could be affecting how the footer renders:
`
<link rel="stylesheet" href="https://ocefpaf.github.io/notebooks_demos/assets/css/main.css">
`
If those can be removed somehow, it might look better.

**Comment by ocefpaf** [comment]
> If those can be removed somehow, it might look better.

I will check what is needed from those. I added them to ensure code highlight and some other changes I made to the notebooks style. Maybe those are not needed. Let me try...

**Comment by ocefpaf** [comment]
@mwengren we probably won't need all of the css that is in 

``` html
<link rel="stylesheet" href="/notebooks_demos/assets/css/syntax.css">
<link rel="stylesheet" href="/notebooks_demos/assets/css/style.css">
```

but a smaller code cell fontsize, the column width adjustments, and probably some other minor adjusts will be needed. I also like my code highlighting better b/c it is closer to what people see in the notebook. Check the version without the css above here: https://ocefpaf.github.io/notebooks_demos/ (and you are correct, the footer is in the right place now.)

But before we try to mix anything from my setup into yours I would like to overwrite everything in this repository with your theme. Then we can gradually inject the extra css I need for the notebooks. That way we avoid breaking any of the current pages in case you decide to use this repo as submodules in other pages too.

**Comment by mwengren** [comment]
@ocefpaf Ok, I had some time to clean up the Catalog theme and made a couple of branches of this repo with the required files to make it work.  

There are two branches I could make a PR from.  The first includes the extra files required to run a Jekyll environment for development on localhost, second only includes files required to build the theme on GitHub pages, with the result out of the box looking like: https://mwengren.github.io/ioos_jekyll_theme/.

I'm not sure which you prefer for the intent of this repo.  Hopefully the submodule feature will still work with these extra files, but some files in the repo root are needed in order for GitHub pages to build the site, namely a _config.yml, and index.html for the root page content.

I'll make a PR for both and let you decide which is better...

**Comment by ocefpaf** [comment]
Thanks @mwengren! I believe the one with the extra files is OK. I will start hacking at this today.

**Comment by lukecampbell** [comment]
Just a heads up I made a small tweak to the style on ioos/catalog which changes the fonts to match the main IOOS site (ioos.noaa.gov). 

https://github.com/ioos/catalog/pull/11

**Comment by ocefpaf** [comment]
To my disappointment symlinks, like I suggested in https://github.com/ioos/ioos_jekyll_theme/issues/4#issuecomment-248070633, will not work with `jekyll` :unamused: 

We will have to find another strategy or brake each component (folder from this repository) into its own repo. I saw the latter in a few sites. We can even keep this repo, using all the components as submodules, to show a rendered version.

I do not like the extra complexity of that solution, but I do not know another solution. What do you think @mwengren and @lukecampbell?

**Comment by lukecampbell** [comment]
I think our hands are tied somewhat since the engine that runs the site is hosted by github so we wouldn't be able to use concepts like submodules, I think. Right now I'm just using `rsync`.

**Comment by ocefpaf** [comment]
> I think our hands are tied somewhat since the engine that runs the site is hosted by github so we wouldn't be able to use concepts like submodules

Not really. It is not able to use a single `submodule`, but if we create repos for each component of the theme (`_data`, `_includes`, `_layouts`, `_pages`, `_sass`, `assets`, and `images`) it would work.

I saw that in many places but, like I said above, I am not a big fan of the extra complexity. So I am on the fence here.

We could still pull this repo in a single submodule and provide a script to `rsync` the components. But this as also a little bit complex. (And we would need to provide that script here to standardize how we perform the syncing.)

**Comment by lukecampbell** [comment]
What is the simplest solution?

**Comment by ocefpaf** [comment]
> What is the simplest solution?

That is exactly my question :smile: 

I am on the fence here. I like the elegance of spiting the repos but I do not like the extra complexity of 7 `submodules`. On the other hand, while the `rsync` script looks simpler, it will cause a duplication of files in the repo.

**Comment by ocefpaf** [comment]
@mwengren what do you think?

**Comment by mwengren** [comment]
@ocefpaf What's the reason that the submodule option doesn't work?  Is it because the of the Jekyll/GitHub pages engine not recognizing the symlinks?  Or something else?

I ask because it looks like those paths can be overridden in _config.yml (from https://jekyllrb.com/docs/configuration/):

# Where things are

source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

Could we just make a copy of _config.yml in this repo (to something like _config_submodule.yml), then modify the source config parameters there to reflect the submodule subdirectories, like:

source:       ioos_jekyll_theme
destination:  ./_site
plugins_dir:  ioos_jekyll_theme/_plugins
layouts_dir:  ioos_jekyll_theme/_layouts
data_dir:     ioos_jekyll_theme/_data
includes_dir: ioos_jekyll_theme/_includes

Then, when the user adds the template as a submodule, they would just have to do an extra step to copy ioos_jekyll_theme/_config_submodule.yml to _config.yml in the root of the repo and maybe GH-Pages would build the site?   It may require some other path changes in some of the files, not sure.

Any chance that might work?

**Comment by ocefpaf** [comment]
>  Is it because the of the Jekyll/GitHub pages engine not recognizing the symlinks?

Yes.

> I ask because it looks like those paths can be overridden in _config.yml (from https://jekyllrb.com/docs/configuration/):

That is a much better solution! I had no idea Jekyll could do that. Testing it now.

Thanks @mwengren!

**Comment by mwengren** [comment]
@ocefpaf I tried a few options for this by tweaking the configuration
options in _config.yml, and I don't think Jekyll is really meant to be run
this way.    Maybe there's a way, I ended up trying a bunch of hacky
approaches and nothing quite worked.

I was able to get a site up and running, just by setting the source
variable in _config.yml and leaving the rest alone.  For ex:

```
source                   : ioos_jekyll_theme
destination              : _site
plugins_dir              : _plugins
layouts_dir              : _layouts
data_dir                 : _data
includes_dir             : _includes

 Sass/SCSS
sass:
  sass_dir               : _sass
  style                  : compressed
```

The consequence of this is that all of the page content (markdown) is
expected to reside under the /ioos_jekyll_theme submodule.  Which means it
can't be detached and maintained in the host repo, which mostly defeats the
purpose.

Jekyll has the concept of custom collections for related content, but after
googling around a bit, it sounds like the various proposals to make a way
to define collections external to the site source dir haven't been accepted
yet:
https://github.com/jekyll/jekyll/pull/3723.  That also means any custom
collection has to be in a directory within 'source' dir with name
'_my_custom_collection_name', which doesn't fix the submodule problem.


I can almost get everything working by hacking some paths and reconfiguring
the settings above to use the host repo root directory as the 'source'
setting for Jekyll, and then using a custom collection in _config.yml
(named 'gh_pages', which allows you to add markdown pages in a directory
'_gh_pages' in the host repo), but the resulting page doesn't show the side
nav menu... not sure why.

Settings for that scenario:
```
source                     : .
destination              : _site
plugins_dir              : ioos_jekyll_theme/_plugins
layouts_dir              : ioos_jekyll_theme/_layouts
data_dir                 : _data
includes_dir             : ioos_jekyll_theme/_includes

# Sass/SCSS
sass:
  sass_dir               : ioos_jekyll_theme/_sass
  style                  : compressed

collections              :
  gh_pages               :
    output               : true
```

Pretty close but not quite.  This approach probably would work, but there's
still some set up to get it working that is pretty hacky.

Any luck?

Micah

**Comment by mwengren** [comment]
@ocefpaf I tried a few options for this by tweaking the configuration
options in _config.yml, and I don't think Jekyll is really meant to be run
this way.    Maybe there's a way, I ended up trying a bunch of hacky
approaches and nothing quite worked.

I was able to get a site up and running, just by setting the source
variable in _config.yml and leaving the rest alone.  For ex:

```
source                   : ioos_jekyll_theme
destination              : _site
plugins_dir              : _plugins
layouts_dir              : _layouts
data_dir                 : _data
includes_dir             : _includes

 Sass/SCSS
sass:
  sass_dir               : _sass
  style                  : compressed
```

The consequence of this is that all of the page content (markdown) is
expected to reside under the /ioos_jekyll_theme submodule.  Which means it
can't be detached and maintained in the host repo, which mostly defeats the
purpose.

Jekyll has the concept of custom collections for related content, but after
googling around a bit, it sounds like the various proposals to make a way
to define collections external to the site source dir haven't been accepted
yet:
https://github.com/jekyll/jekyll/pull/3723.  That also means any custom
collection has to be in a directory within 'source' dir with name
'_my_custom_collection_name', which doesn't fix the submodule problem.

I can almost get everything working by hacking some paths and reconfiguring
the settings above to use the host repo root directory as the 'source'
setting for Jekyll, and then using a custom collection in _config.yml
(named 'gh_pages', which allows you to add markdown pages in a directory
'_gh_pages' in the host repo), but the resulting page doesn't show the side
nav menu... not sure why.

Settings for that scenario:

```
source                     : .
destination              : _site
plugins_dir              : ioos_jekyll_theme/_plugins
layouts_dir              : ioos_jekyll_theme/_layouts
data_dir                 : _data
includes_dir             : ioos_jekyll_theme/_includes

# Sass/SCSS
sass:
  sass_dir               : ioos_jekyll_theme/_sass
  style                  : compressed

collections              :
  gh_pages               :
    output               : true
```

Pretty close but not quite.  This approach probably would work, but there's
still some set up to get it working that is pretty hacky.

Any luck?

Micah

**Comment by mwengren** [comment]
@ocefpaf hah, I was fooled by the same typo as you, I had 'gh-pages' in the _config.yml file rather than 'gh_pages', which is what I named my collection.  The second hacky approach I mentioned before works now, although I don't know if it's straightforward enough to be worthwhile. 

https://github.com/mwengren/WorldWeatherSymbols/tree/gh-pages.  

Local markdown page content can be saved in whatever custom Jekyll collection folder you want, I used '_gh_pages' for mine.  You also have to copy the /data, _config.yml, and index.html files from the submodule and configure accordingly. 

It's not the best repo to use as an example due to files already there, but that's the process outline.

Example pages : https://mwengren.github.io/WorldWeatherSymbols/.

This is the page saved in my WorldWeatherSymbols repo: https://mwengren.github.io/WorldWeatherSymbols/gh_pages/readme_test/.

I created another branch of the ioos_jekyll_theme to hold the changes (hacks) required in the template for this approach to work: 

https://github.com/ioos/ioos_jekyll_theme/tree/gh-pages-submodule

Hopefully there's a better way... or do you think this is practical?

**Comment by ocefpaf** [comment]
> Hopefully there's a better way... or do you think this is practical?

I do not know of any other better way. I agree that this is not the best way but I think it is better than `rsync` or multiple submodules and I I am OK with that.

**Comment by ocefpaf** [comment]
Do you want to send a PR with your modifications?

**Comment by ocefpaf** [comment]
Closing this as we will need a "clean" issue to show how to use this theme.
